### ISSUE TITLE
The mod is incredible, but I have a few points against it.

### ISSUE THREAD

**Issue by qVoidreaver** [dfdyz/epicacg-1.18#1]
Hello, I have to congratulate you on the evolution compared to the previous project, it really is VERY good.

 But I have to give some counterpoints and the main one is the optimization, I don't particularly care about the "tracks" (because they are removable) of the weapons, but the effects of the wings cause a huge fps lag (even if I remove the textures manually or by resource pack), if you can solve this or add an option to remove it in the settings (it would be good for weak PCs) I would appreciate it.

 Another point would be in relation to the "Rapier" fighting style, the knockback from running and attacking is very high, and the same goes for the rapier ability when used while moving.
 
 [Suggestion]
 
What do you think about the rapier's Dash Hit applying the "hit_long" stun animation instead of the "knockdown" animation?

**Comment by dfdyz** [comment]
effect of wings is removeable too. use resource pack and patch the animation effect define(on .\data at same path as same name)
the bloom vfx is use some post effect shader, it may not friendly to some low pc.

for weapon balance: those weapon are designed to "mow mob". i will not decrease their effect and parameter
